# Scheme 設定
scheme: Gemini

# 深色模式
darkmode: true

# 選單設定
menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  about: /about/ || fa fa-user

# 側邊欄設定
sidebar:
  position: left
  display: post

# 文章設定
post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: true
    another_day: true
  categories: true
  symbols_count_time: true    # 字數統計

# 字數統計設定
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false

# 回到頂部
back2top:
  enable: true
  sidebar: false
  scrollpercent: true

# 本地搜尋
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 3
  unescape: false
  preload: false

# PJAX
pjax: true

# CDN 設定
vendors:
  plugins: unpkg